### ISSUE TITLE
是不是得注册个右键菜单啊? 

### ISSUE THREAD

**Issue by llxwj** [xiaozhuai/thunder-download-manager#1]
我现在点击下载链接没反应了. 原来是Chrom 底部会提示下载进度的, 加个有键菜单,把下载链接传到你的下载器吧.

**Comment by xiaozhuai** [comment]
<img width="1029" alt="WeChat38f5b8332bb4eb4b1603b927e1860843" src="https://user-images.githubusercontent.com/4773701/62285134-9aab1a00-b487-11e9-9672-b38422f58404.png">

你点下这个图标看看

**Comment by llxwj** [comment]
刚安装完点击下载链接, 扩展程序的"闪电"图标的右下角, 真的是没有数字角标的. 现在换了一个电脑后,出现了,这个扩展是Chrome自动同步安装的,

**Comment by xiaozhuai** [comment]
这个问题应该在0.1.3版本修复了，现在上线的是0.1.2版，0.1.3还在审核，之后更新试试应该能解决

**Comment by llxwj** [comment]
好的!
